// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAymQBypJp_qWe1uf7-o8q8cdD19hZ1Wak',
    appId: '1:290006438607:web:8480dc74772a1394875dba',
    messagingSenderId: '290006438607',
    projectId: 'flutter-login-6a87b',
    authDomain: 'flutter-login-6a87b.firebaseapp.com',
    storageBucket: 'flutter-login-6a87b.appspot.com',
    measurementId: 'G-C189H4MTZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjJmXOZ_BjuH0xb2290PHXmMKMoTXaxxc',
    appId: '1:290006438607:android:ea9859b28eb56056875dba',
    messagingSenderId: '290006438607',
    projectId: 'flutter-login-6a87b',
    storageBucket: 'flutter-login-6a87b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxA4jbS_V1a4ttv_CXT7fQqh5cGG3BVgI',
    appId: '1:290006438607:ios:e8f0f96364a618a9875dba',
    messagingSenderId: '290006438607',
    projectId: 'flutter-login-6a87b',
    storageBucket: 'flutter-login-6a87b.appspot.com',
    iosClientId: '290006438607-p5sodpp0vaplbv6dgc5oilj99cf86sdg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDev',
  );
}
